name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 2.0.2
homepage: https://github.com/gcappon/fitbitter

environment:
  sdk: '>=2.18.0 <4.0.0'
  #flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_auth: ^0.6.0 #used to implement oauth 2.0
  dio: 5.4.0

  logger: ^1.3.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
